# Generated by Django 4.0.6 on 2022-07-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='中文简称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('establishment', models.CharField(max_length=100, verbose_name='成立时间')),
                ('marketTime', models.CharField(max_length=100, verbose_name='上市时间')),
                ('openingPrice', models.CharField(max_length=100, verbose_name='开盘价')),
                ('closingPrice', models.CharField(max_length=100, verbose_name='开盘价')),
            ],
        ),
    ]
