# Generated by Django 4.0.6 on 2022-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='中文简称')),
                ('date', models.CharField(max_length=100, verbose_name='日期')),
                ('open', models.CharField(max_length=100, verbose_name='开盘价')),
                ('min', models.CharField(max_length=100, verbose_name='最低价')),
                ('max', models.CharField(max_length=100, verbose_name='收盘价')),
                ('upDown', models.CharField(max_length=100, verbose_name='涨跌额')),
                ('Quote', models.CharField(max_length=100, verbose_name='涨跌幅')),
                ('volume', models.CharField(max_length=100, verbose_name='成交量')),
                ('Turnover', models.CharField(max_length=100, verbose_name='成交金额')),
                ('amplitude', models.CharField(max_length=100, verbose_name='振幅')),
                ('TurnoverRate', models.CharField(max_length=100, verbose_name='换手率')),
            ],
        ),
    ]
