# Generated by Django 4.0.6 on 2022-07-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wealth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('name', 'address')},
        ),
    ]
