# Generated by Django 4.0.6 on 2022-07-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_info_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='info',
            unique_together=set(),
        ),
    ]
