# Generated by Django 4.0.6 on 2022-07-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wealth_unique_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wealth',
            name='name',
            field=models.CharField(max_length=100, verbose_name='中文简称'),
        ),
    ]
