# Generated by Django 4.0.6 on 2022-07-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_sector_marketprice_remove_sector_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='geo',
            field=models.CharField(default=1, max_length=100, verbose_name='省份'),
            preserve_default=False,
        ),
    ]
