# Generated by Django 4.0.6 on 2022-07-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_sector_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='geo',
        ),
    ]
