# Generated by Django 4.0.6 on 2022-07-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sector_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wealth',
            name='close',
            field=models.CharField(default=1, max_length=100, verbose_name='收盘价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wealth',
            name='max',
            field=models.CharField(max_length=100, verbose_name='最高价'),
        ),
    ]
